baseURL = "http://www.rkinneavy.com/"
languageCode = "en-GB"
title = "Rowan's Place"
theme = "book"


[params]
# BookDateFormat = '2006-01-02'
BookSearch = true
BookComments = false
enableGitInfo = true
# BookMenuBundle = "/menu"

[markup]
# Mostly defaults below
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      # unsafe = true since we'll be using 'unsafe' inline HTML
      unsafe = true
      xHTML = false


[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
