baseURL = "http://www.rkinneavy.com/"
languageCode = "en-GB"
title = "Rowan's Place"
theme = "book"


[params]
# BookDateFormat = '2006-01-02'
BookSearch = false
BookComments = false
enableGitInfo = true
# BookMenuBundle = "/menu"


[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
